import{getStore}from"@netlify/blobs";import{marked}from"marked";import sanitizeHtml from"sanitize-html";import{randomUUID}from"node:crypto";
export const postStore=()=>getStore("firebird-blog-posts"),imageStore=()=>getStore("firebird-blog-images");
export const json=(statusCode,value,headers={})=>({statusCode,headers:{"content-type":"application/json; charset=utf-8",...headers},body:JSON.stringify(value)});
export const text=(statusCode,body,headers={})=>({statusCode,headers:{"content-type":"text/plain; charset=utf-8",...headers},body});
export const cleanSlug=(v="")=>String(v).toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
function parseEasternPublishDate(value){if(value instanceof Date||typeof value==="number")return new Date(value).toISOString();const v=String(value);if(/[zZ]$|[+-]\d\d:\d\d$/.test(v))return new Date(v).toISOString();const m=v.match(/^(\d{4})-(\d{2})-(\d{2})(?:T(\d{2}):(\d{2})(?::(\d{2}))?)?$/);if(!m)return new Date(v).toISOString();const [,y,mo,da,h="07",mi="00",s="00"]=m,n=Date.UTC(+y,+mo-1,+da,+h,+mi,+s),fmt=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",timeZoneName:"shortOffset"}).formatToParts(new Date(n)),off=fmt.find(p=>p.type==="timeZoneName")?.value||"GMT-4",om=off.match(/GMT([+-])(\d{1,2})(?::(\d{2}))?/),mins=om?(om[1]==="-"?-1:1)*(+om[2]*60 + +(om[3]||0)):-240;return new Date(n-mins*60000).toISOString()}
export function normalizePost(i,e={}){const title=String(i.title||"").trim(),slug=cleanSlug(i.slug||title),description=String(i.description||"").trim(),body=String(i.body||"");if(!title||!slug||!description||!body)throw Error("Title, URL name, summary, and article are required.");return{id:e.id||i.id||randomUUID(),title,slug,description,author:String(i.author||"Dr. Mark Hagen").trim(),date:parseEasternPublishDate(i.date||Date.now()),status:["published","scheduled"].includes(i.status)?i.status:"draft",featuredImage:String(i.featuredImage||""),imageAlt:String(i.imageAlt||"").trim(),body,createdAt:e.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()}}
export const publicPost=p=>({...p,bodyHtml:sanitizeHtml(marked.parse(p.body),{allowedTags:sanitizeHtml.defaults.allowedTags.concat(["img"]),allowedAttributes:{a:["href","title","target","rel"],img:["src","alt","title"]},allowedSchemes:["http","https","mailto"]})});
export async function listPosts(){const s=postStore(),{blobs=[]}=await s.list(),a=[];for(const b of blobs){const p=await s.get(b.key,{type:"json"});if(p)a.push(p)}return a.sort((x,y)=>new Date(y.date)-new Date(x.date))}
export async function handler(){return text(404,"Not found")}
